# Check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
    # Path to main.go file or main package.
    # Default is `.`.
    main: '.'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^doc[s]?:'
      - '^\[doc[s]?\]'
      - '^[wW][iI][pP]:'
      - '^[tT][eE][sS][tT]:'
nfpms:
  - id: ohman
    package_name: ohman
    homepage: https://github.com/jimschubert/ohman
    maintainer: Jim Schubert <jim.schubert@gmail.com>
    description: A tool to manage duplicate files.
    license: APACHE-2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/local/bin
# temporarily disabled until I decide I want to push to tap.
#brews:
#  - repository:
#      owner: jimschubert
#      name: homebrew-tap
#      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#    homepage: "https://github.com/jimschubert/ohman"
#    description: "A tool to manage duplicate files."
#    license: "Apache-2.0"
#    commit_author:
#      name: goreleaserbot
#      email: bot@goreleaser.com
